apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-server
  namespace: default
  labels:
    app: greeter-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter-server
  template:
    metadata:
      namespace: default
      labels:
        app: greeter-server
    spec:
      containers:
      - name: greeter-server
        image: localhost:32000/greeter-server
        imagePullPolicy: Always
        args: ["--addr0, ":8123"]
# TODO: montar volumes
# TODO: spiff endpoint env
---
apiVersion: v1
kind: Service
metadata:
  name: greeter-server
  namespace: default
spec:
  selector:
    app: greeter-server
  type: LoadBalancer
  ports:
  - name: api
    port: 8123
    targetPort: 8123
    protocol: TCP
