apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-server
  namespace: default
  labels:
    app: greeter-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter-server
  template:
    metadata:
      namespace: default
      labels:
        app: greeter-server
    spec:
      containers:
      - name: greeter-server
        image: registry-service:32000/greeter-server:demo
        imagePullPolicy: Always
        args: ["--addr", ":8123"] 
# TODO: montar volumes
# TODO: spiff endpoint env
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec:
  selector:
    app: registry  # Use os rótulos do seu pod de registro
  ports:
    - protocol: TCP
      port: 32000     # A porta em que o registro está exposto no pod
---
apiVersion: v1
kind: Service
metadata:
  name: greeter-server
  namespace: default
spec:
  selector:
    app: greeter-server
  type: LoadBalancer
  ports:
  - name: api
    port: 8123
    targetPort: 8123
    protocol: TCP

